import React from 'react';
import { Business, Story, FeedPost, HeroSlide, Category, Governorate, Notification, User } from './types';

export const APP_COLORS = {
  PRIMARY: '#FF6B6B',
  SECONDARY: '#4ECDC4',
  BACKGROUND: '#FFF5E6',
  SURFACE: '#FFFFFF',
  TEXT_PRIMARY: '#2D2D2D',
  TEXT_SECONDARY: '#8A8A8A',
  TEXT_MUTED: '#BDBDBD',
  BORDER: '#EEEEEE',
  SHADOW: 'rgba(0,0,0,0.08)',
  PREMIUM_GOLD: '#F6C90E',
  LIVE_RED: '#FF3B30',
  SUCCESS: '#34C759',
  UNREAD_BG: '#FFF5F5',
};

export const TYPOGRAPHY = {
  headline: { fontFamily: "'Cairo', sans-serif", fontWeight: 700 },
  body: { fontFamily: "'IBM Plex Sans Arabic', sans-serif", fontWeight: 400 },
};

export const TRANSLATIONS = {
  en: {
    appName: 'Iraq Compass',
    shakumaku: 'Shakumaku',
    madinaty: 'My City',
    loadMore: 'Load More',
    viewBusiness: 'View Business',
    addPost: 'Add Post',
    search: 'Search businesses, places...',
    followers: 'Followers',
    following: 'Following',
    posts: 'Posts',
    openNow: 'Open Now',
    closed: 'Closed',
    premium: 'Premium',
    verified: 'Verified',
    activeToday: 'Active Today',
    recentlyUpdated: 'Recently Updated',
    call: 'Call',
    directions: 'Directions',
    reviews: 'Reviews',
    about: 'About',
    photos: 'Photos',
    map: 'Map',
    share: 'Share',
    save: 'Save',
    back: 'Back',
    reply: 'Reply...',
    sendComment: 'Send',
    notifications: 'Notifications',
    profile: 'Profile',
    settings: 'Settings',
    language: 'Language',
    darkMode: 'Dark Mode',
    signOut: 'Sign Out',
    myPosts: 'My Posts',
    savedBusinesses: 'Saved Businesses',
    markAllRead: 'Mark All Read',
    today: 'Today',
    yesterday: 'Yesterday',
    edit: 'Edit',
    all: 'All',
    cafes: 'Cafes',
    restaurants: 'Restaurants',
    gyms: 'Gyms',
    clinics: 'Clinics',
    hotels: 'Hotels',
    shopping: 'Shopping',
    beauty: 'Beauty',
    services: 'Services',
    pharmacies: 'Pharmacies',
    schools: 'Schools',
    malls: 'Malls',
    parks: 'Parks',
    entertainment: 'Entertainment',
    electronics: 'Electronics',
    markets: 'Markets',
    libraries: 'Libraries',
    theaters: 'Theaters',
    bakeries: 'Bakeries',
    whatsapp: 'WhatsApp',
    description: 'Description',
    writeReview: 'Write a Review',
    callNow: 'Call Now',
    visitWebsite: 'Visit Website',
    noData: 'Error: No data',
    reviewsCount: 'reviews',
  },
  ar: {
    appName: 'بوصلة العراق',
    shakumaku: 'شكومكو',
    madinaty: 'مدينتي',
    loadMore: 'تحميل المزيد',
    viewBusiness: 'عرض المحل',
    addPost: 'إضافة منشور',
    search: 'ابحث عن أماكن...',
    followers: 'متابعون',
    following: 'يتابع',
    posts: 'منشورات',
    openNow: 'مفتوح الآن',
    closed: 'مغلق',
    premium: 'مميز',
    verified: 'موثق',
    activeToday: 'نشط اليوم',
    recentlyUpdated: 'تم التحديث مؤخراً',
    call: 'اتصال',
    directions: 'الاتجاهات',
    reviews: 'المراجعات',
    about: 'حول',
    photos: 'الصور',
    map: 'الخريطة',
    share: 'مشاركة',
    save: 'حفظ',
    back: 'رجوع',
    reply: 'رد...',
    sendComment: 'إرسال',
    notifications: 'التنبيهات',
    profile: 'الملف الشخصي',
    settings: 'الإعدادات',
    language: 'اللغة',
    darkMode: 'الوضع الليلي',
    signOut: 'تسجيل الخروج',
    myPosts: 'منشوراتي',
    savedBusinesses: 'المحلات المحفوظة',
    markAllRead: 'تحديد الكل كمقروء',
    today: 'اليوم',
    yesterday: 'أمس',
    edit: 'تعديل',
    all: 'الكل',
    cafes: 'مقاهي',
    restaurants: 'مطاعم',
    gyms: 'صالات رياضة',
    clinics: 'عيادات',
    hotels: 'فنادق',
    shopping: 'تسوق',
    beauty: 'تجميل',
    services: 'خدمات',
    pharmacies: 'صيدليات',
    schools: 'مدارس',
    malls: 'مولات',
    parks: 'منتزهات',
    entertainment: 'ترفيه',
    electronics: 'إلكترونيات',
    markets: 'أسواق',
    libraries: 'مكتبات',
    theaters: 'مسارح',
    bakeries: 'مخابز',
    whatsapp: 'واتساب',
    description: 'الوصف',
    writeReview: 'كتابة مراجعة',
    callNow: 'اتصل الآن',
    visitWebsite: 'زيارة الموقع',
    noData: 'خطأ: لا توجد بيانات',
    reviewsCount: 'مراجعة',
  },
  ku: {
    appName: 'کۆمپاسی عێراق',
    shakumaku: 'شکومکو',
    madinaty: 'شارەکەم',
    loadMore: 'زیاتر بکەوە',
    viewBusiness: 'بینینی کاروبار',
    addPost: 'پۆست زیاد بکە',
    search: 'گەڕان بکە...',
    followers: 'فۆڵۆوەران',
    following: 'فۆڵۆوینگ',
    posts: 'پۆستەکان',
    openNow: 'ئێستا کراوەیە',
    closed: 'داخراوە',
    premium: 'نایاب',
    verified: 'پشتڕاستکراوە',
    activeToday: 'ئەمڕۆ چالاکە',
    recentlyUpdated: 'بەم دواییانە نوێکراوەتەوە',
    call: 'پەیوەندی',
    directions: 'ئاراستەکان',
    reviews: 'پێداچوونەوەکان',
    about: 'دەربارە',
    photos: 'وێنەکان',
    map: 'نەخشە',
    share: 'هاوبەشکردن',
    save: 'پاشەکەوتکردن',
    back: 'گەڕانەوە',
    reply: 'وەڵامدانەوە...',
    sendComment: 'ناردن',
    notifications: 'ئاگادارکردنەوەکان',
    profile: 'پرۆفایل',
    settings: 'ڕێکخستنەکان',
    language: 'زمان',
    darkMode: 'دۆخی تاریک',
    signOut: 'چوونە دەرەوە',
    myPosts: 'پۆستەکانم',
    savedBusinesses: 'کاروبارە پاشەکەوتکراوەکان',
    markAllRead: 'هەمووی وەک خوێندراوە نیشان بدە',
    today: 'ئەمڕۆ',
    yesterday: 'دوێنێ',
    edit: 'دەستکاری',
    all: 'هەموو',
    cafes: 'کافێکان',
    restaurants: 'چێشتخانەکان',
    gyms: 'هۆڵەکانی وەرزش',
    clinics: 'کلینیکەکان',
    hotels: 'ئوتێلەکان',
    shopping: 'بازاڕکردن',
    beauty: 'جوانکاری',
    services: 'خزمەتگوزارییەکان',
    pharmacies: 'دەرمانخانەکان',
    schools: 'قوتابخانەکان',
    malls: 'مۆڵەکان',
    parks: 'پارکەکان',
    entertainment: 'کات بەسەربردن',
    electronics: 'ئەلیکترۆنیات',
    markets: 'بازاڕەکان',
    libraries: 'کتێبخانەکان',
    theaters: 'شانۆکان',
    bakeries: 'نانەواخانەکان',
    whatsapp: 'واتساب',
    description: 'وەسف',
    writeReview: 'پێداچوونەوە بنووسە',
    callNow: 'ئێستا پەیوەندی بکە',
    visitWebsite: 'سەردانی ماڵپەڕ بکە',
    noData: 'هەڵە: زانیاری نییە',
    reviewsCount: 'پێداچوونەوە',
  },
};

export const GOVERNORATES: Governorate[] = [
  { id: 'baghdad', name: { en: 'Baghdad', ar: 'بغداد', ku: 'بەغدا' } },
  { id: 'basra', name: { en: 'Basra', ar: 'البصرة', ku: 'بەسرە' } },
  { id: 'erbil', name: { en: 'Erbil', ar: 'أربيل', ku: 'هەولێر' } },
  { id: 'sulaymaniyah', name: { en: 'Sulaymaniyah', ar: 'السليمانية', ku: 'سلێمانی' } },
  { id: 'najaf', name: { en: 'Najaf', ar: 'النجف', ku: 'نەجەف' } },
  { id: 'karbala', name: { en: 'Karbala', ar: 'كربلاء', ku: 'کەربەلا' } },
  { id: 'kirkuk', name: { en: 'Kirkuk', ar: 'كركوك', ku: 'کەرکوک' } },
  { id: 'mosul', name: { en: 'Mosul', ar: 'الموصل', ku: 'مووسڵ' } },
  { id: 'duhok', name: { en: 'Duhok', ar: 'دهوك', ku: 'دهۆک' } },
];

export const HERO_SLIDES: HeroSlide[] = [
  {
    id: 1,
    title: "أفضل المقاهي في بغداد",
    subtitle: "Trending Cafes in Baghdad",
    image: "https://picsum.photos/seed/cafe-baghdad/800/400",
  },
  {
    id: 2,
    title: "مطاعم اليوم المميزة",
    subtitle: "Best Restaurants Today",
    image: "https://picsum.photos/seed/restaurant-iraq/800/400",
  },
  {
    id: 3,
    title: "الجواهر الخفية في السليمانية",
    subtitle: "Hidden Gems in Sulaymaniyah",
    image: "https://picsum.photos/seed/sulaymaniyah-city/800/400",
  },
];

export const MOCK_USERS: User[] = [
  { id: 'u1', name: 'User Name', avatar: 'https://picsum.photos/seed/u1/100/100', email: 'user@email.com' },
  { id: 'u2', name: 'سارة محمد', avatar: 'https://picsum.photos/seed/u2/100/100', email: 'sara@example.com' },
];

export const CATEGORIES: Category[] = [
  { id: 'all', icon: '🏙️', nameKey: 'all', eventCount: 0 },
  { id: 'cafes', icon: '☕', nameKey: 'cafes', eventCount: 24, recommended: true,
    subcategories: [
      { id: 'espresso-bars', icon: '☕', nameKey: 'espressoBars' },
      { id: 'traditional', icon: '🫖', nameKey: 'traditionalCafe' },
      { id: 'rooftop', icon: '🏙️', nameKey: 'rooftopCafe' },
    ]
  },
  { id: 'restaurants', icon: '🍽️', nameKey: 'restaurants', eventCount: 47,
    subcategories: [
      { id: 'iraqi', icon: '🫕', nameKey: 'iraqiFood' },
      { id: 'grills', icon: '🔥', nameKey: 'grills' },
      { id: 'seafood', icon: '🐟', nameKey: 'seafood' },
      { id: 'pizza', icon: '🍕', nameKey: 'pizza' },
    ]
  },
  { id: 'gyms', icon: '💪', nameKey: 'gyms', eventCount: 12 },
  { id: 'clinics', icon: '🏥', nameKey: 'clinics', eventCount: 31 },
  { id: 'hotels', icon: '🏨', nameKey: 'hotels', eventCount: 18 },
  { id: 'shopping', icon: '🛍️', nameKey: 'shopping', eventCount: 55, recommended: true },
];

export const MOCK_BUSINESSES: Business[] = [
  {
    id: 'b1', name: 'Green Garden Cafe', nameAr: 'مقهى الحديقة الخضراء',
    nameKu: 'کافێی بُستانی سەوز',
    coverImage: 'https://picsum.photos/seed/cafe-coffee/400/400',
    isPremium: true, isFeatured: true, category: 'cafes', subcategory: 'rooftop',
    rating: 4.8, reviewCount: 247, verified: true, isVerified: true,
    governorate: 'baghdad', city: 'Karrada',
    address: 'Karrada St., Baghdad', phone: '+964 770 111 2233',
    whatsapp: '9647701112233',
    description: 'Premium rooftop cafe with specialty coffee and panoramic Baghdad views.',
    descriptionAr: 'مقهى فاخر على السطح مع قهوة متخصصة وإطلالات بانورامية على بغداد.',
    openHours: '8 AM – 12 AM', priceRange: 3,
    tags: ['rooftop', 'specialty-coffee', 'wifi', 'delivery'],
    status: 'Active Today', distance: 0.8, lat: 33.3152, lng: 44.3661,
  },
  {
    id: 'b2', name: 'Baghdad Grill', nameAr: 'مشاوي بغداد', nameKu: 'گرێلی بەغدا',
    coverImage: 'https://picsum.photos/seed/grill-restaurant/400/400',
    isPremium: false, isFeatured: true, category: 'restaurants', subcategory: 'grills',
    rating: 4.6, reviewCount: 512, verified: true, isVerified: true,
    governorate: 'baghdad', city: 'Mansour',
    address: 'Mansour, Baghdad', phone: '+964 780 222 3344',
    description: 'Authentic Iraqi grills in the heart of Mansour.',
    descriptionAr: 'مشاوي عراقية أصيلة في قلب المنصور.',
    openHours: '12 PM – 2 AM', priceRange: 2,
    tags: ['grills', 'iraqi-food', 'family', 'dine-in'],
    status: 'Recently Updated', distance: 1.2, lat: 33.3265, lng: 44.3788,
  },
  {
    id: 'b3', name: 'Blue Gym', nameAr: 'بلو جيم', nameKu: 'جیمی شین',
    coverImage: 'https://picsum.photos/seed/gym-fitness/400/400',
    isPremium: true, isFeatured: false, category: 'gyms',
    rating: 4.9, reviewCount: 189, verified: true, isVerified: true,
    governorate: 'baghdad', city: 'Jadriyah',
    address: 'Jadriyah, Baghdad', phone: '+964 750 333 4455',
    description: 'State-of-the-art gym with personal trainers and classes.',
    openHours: '6 AM – 11 PM', priceRange: 3,
    tags: ['gym', 'personal-trainer', 'classes', 'pool'],
    status: 'Active Today', distance: 2.1,
  },
];

export const MOCK_STORIES: Story[] = [
  {
    id: 1,
    avatar: 'https://i.pravatar.cc/80?img=1',
    name: 'Green Garden',
    viewed: false,
    verified: true,
    thumbnail: 'https://picsum.photos/seed/cafe/200/300',
    userName: 'greengarden_bgh',
    type: 'business',
    aiVerified: true,
    isLive: false,
    media: ['https://picsum.photos/seed/coffee/400/700'],
    timeAgo: '2m ago',
  },
  {
    id: 2,
    avatar: 'https://i.pravatar.cc/80?img=5',
    name: 'Baghdad Grill',
    viewed: false,
    verified: true,
    thumbnail: 'https://picsum.photos/seed/grill/200/300',
    userName: 'baghdadgrill',
    type: 'business',
    aiVerified: false,
    isLive: true,
    media: ['https://picsum.photos/seed/food/400/700'],
    timeAgo: '5m ago',
  },
];

export const MOCK_FEED_POSTS: FeedPost[] = [
  {
    id: 1, businessId: 'b1', businessName: 'Green Garden Cafe',
    businessNameAr: 'مقهى الحديقة الخضراء',
    avatar: 'https://i.pravatar.cc/60?img=1',
    category: 'Cafe', timeAgo: '1h ago',
    caption: 'Try our new espresso blend ☕ Now available all day!',
    captionAr: 'جربوا خلطة الإسبريسو الجديدة ☕ متوفرة طوال اليوم!',
    media: 'https://picsum.photos/seed/coffee/600/400',
    mediaType: 'image', likes: 247, comments: 34, isLiked: false,
    verified: true, governorate: 'baghdad'
  },
  {
    id: 2, businessId: 'b2', businessName: 'Baghdad Grill',
    businessNameAr: 'مشاوي بغداد',
    avatar: 'https://i.pravatar.cc/60?img=5',
    category: 'Restaurant', timeAgo: '2h ago',
    caption: '🔥 20% discount tonight only! Bring your family.',
    captionAr: '🔥 خصم ٢٠٪ الليلة فقط! تعالوا مع عائلتكم.',
    media: 'https://picsum.photos/seed/grilled/600/400',
    mediaType: 'reel', likes: 891, comments: 102, isLiked: true,
    verified: true, governorate: 'baghdad'
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  { id: 'n1', title: 'Green Garden Cafe', message: 'liked your post', timestamp: '1h ago', read: false, type: 'like', section: 'today' },
  { id: 'n2', title: 'New comment', message: '"Amazing place!"', timestamp: '2h ago', read: false, type: 'comment', section: 'today' },
];
